name: Deploy docker compose

on:
  workflow_call:
    secrets:
      SECRETS_JSON:
        required: true

env:
  DOCKER_HOST: "ssh://${{ vars.SSH_REMOTE_USER }}@${{ vars.SSH_REMOTE_HOST }}"

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Expose github environment as shell variables
        env:
          SECRETS_CONTEXT: ${{ secrets.SECRETS_JSON }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          to_envs() { jq -r "to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""; }
          echo "$SECRETS_CONTEXT" | to_envs >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH Setup Action
        uses: RedNoodlesOrg/rednet-actions-cloudflared-ssh@main
      - name: Docker
        run: docker compose up -d