name: Deploy docker compose

on:
  workflow_call:

env:
  DOCKER_HOST: "ssh://${{ vars.SSH_REMOTE_USER }}@${{ vars.SSH_REMOTE_HOST }}"
  SSH_REMOTE_HOST: ${{ vars.SSH_REMOTE_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  CLOUDFLARED_ID: ${{ secrets.CLOUDFLARED_ID }}
  CLOUDFLARED_SECRET: ${{ secrets.CLOUDFLARED_SECRET }}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        uses: RedNoodlesOrg/rednet-actions-cloudflared-ssh@main
      - name: Expose github environment as shell variables
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          to_envs() { jq -r "to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""; }
          echo "$VARS_CONTEXT" | to_envs >> $GITHUB_ENV
          echo "$SECRETS_CONTEXT" | to_envs >> $GITHUB_ENV
      - name: Docker
        run: docker compose up -d