name: Test reusable workflow

on:
    workflow_dispatch: 
jobs:
    test:
        uses: RedNoodlesOrg/rednet-actions-workflows/.github/workflows/docker-compose-deploy.yml@main
        with:
            SSH_REMOTE_HOST: ${{ vars.SSH_REMOTE_HOST }}
            SSH_REMOTE_USER: ${{ vars.SSH_REMOTE_USER }}
        secrets:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            CLOUDFLARED_ID: ${{ secrets.CLOUDFLARED_ID }}
            CLOUDFLARED_SECRET: ${{ secrets.CLOUDFLARED_SECRET }}